// Fallback data for when Sanity CMS is not connected
// Uses picsum.photos for placeholder images

export const fallbackSettings = {
  heroHeadline: "Reliable Packaging Solutions for Industrial India",
  heroSubtext: "ISO certified manufacturer with 40+ years of experience. 72,000 MT annual capacity across Chennai and Gujarat.",
  stats: [
    { number: "40+", label: "Years Experience" },
    { number: "72,000", label: "MT Annual Capacity" },
    { number: "2", label: "Manufacturing Plants" },
    { number: "9", label: "Product Lines" },
  ],
  aboutText: "Divine Packaging Industry has been a trusted name in industrial packaging for over four decades. With manufacturing facilities across Tamil Nadu and Gujarat, we deliver consistent, high-quality packaging solutions to some of India's largest industrial enterprises. Our commitment to quality is backed by ISO 9001 certification and a dedicated team of packaging professionals.",
};

export const fallbackProducts = [
  {
    _id: "1",
    name: "Wooden Pallets",
    slug: { current: "wooden-pallets" },
    description: "Heavy-duty wooden pallets engineered for industrial logistics. Available in standard and custom sizes to meet your specific requirements. Built with kiln-dried hardwood for maximum durability and load-bearing capacity.",
    category: "Wood Products",
    mainImage: "/images/products/wooden-pallets.png",
    specs: [
      { label: "Material", value: "Kiln-dried Hardwood" },
      { label: "Load Capacity", value: "Up to 2000 kg" },
      { label: "Sizes", value: "Standard & Custom" },
      { label: "Treatment", value: "ISPM-15 Compliant" },
      { label: "Finish", value: "Heat Treated / Fumigated" },
    ],
    industries: ["Automotive", "Manufacturing", "Logistics"],
  },
  {
    _id: "2",
    name: "Plywood Boxes",
    slug: { current: "plywood-boxes" },
    description: "Lightweight yet sturdy plywood boxes for safe transportation of goods. Ideal for export packaging with ISPM-15 compliance. Custom dimensions and reinforcement options available.",
    category: "Wood Products",
    mainImage: "/images/products/plywood-boxes.png",
    specs: [
      { label: "Material", value: "BWR Grade Plywood" },
      { label: "Thickness", value: "6mm to 19mm" },
      { label: "Joints", value: "Screwed & Stapled" },
      { label: "Lining", value: "Optional EPE/Foam" },
      { label: "Compliance", value: "ISPM-15" },
    ],
    industries: ["Electronics", "Export", "Engineering"],
  },
  {
    _id: "3",
    name: "Corrugated Boxes",
    slug: { current: "corrugated-boxes" },
    description: "High-strength corrugated packaging for industrial and commercial applications. Multi-wall options available for heavy-duty protection. Custom printing and branding available.",
    category: "Paper Products",
    mainImage: "/images/products/corrugated-boxes.png",
    specs: [
      { label: "Flute Type", value: "B, C, BC, E" },
      { label: "Ply", value: "3-ply to 7-ply" },
      { label: "Burst Strength", value: "Up to 20 kg/cm²" },
      { label: "Printing", value: "Flexo / Offset" },
      { label: "Custom Sizes", value: "Available" },
    ],
    industries: ["FMCG", "Pharmaceuticals", "E-commerce"],
  },
  {
    _id: "4",
    name: "Timber Crates",
    slug: { current: "timber-crates" },
    description: "Heavy-duty timber crates designed for the safe packaging of heavy machinery and industrial equipment. Engineered with precision for maximum protection during transit.",
    category: "Wood Products",
    mainImage: "/images/products/timber-crates.png",
    specs: [
      { label: "Material", value: "Premium Timber" },
      { label: "Weight Capacity", value: "Up to 5000 kg" },
      { label: "Construction", value: "Bolt & Screw" },
      { label: "Base", value: "Skid / Pallet" },
      { label: "Custom Design", value: "Yes" },
    ],
    industries: ["Heavy Engineering", "Power", "Oil & Gas"],
  },
  {
    _id: "5",
    name: "HDPE Packaging",
    slug: { current: "hdpe-packaging" },
    description: "Durable HDPE packaging solutions for chemical and industrial applications. Resistant to moisture, chemicals, and UV radiation. Available in drums, containers, and custom shapes.",
    category: "Polymer Products",
    mainImage: "/images/products/hdpe-packaging.png",
    specs: [
      { label: "Material", value: "HDPE / PP" },
      { label: "Capacity", value: "5L to 250L" },
      { label: "Closure", value: "Screw Cap / Bung" },
      { label: "UN Certified", value: "Available" },
      { label: "Color Options", value: "Multiple" },
    ],
    industries: ["Chemicals", "Lubricants", "Paints"],
  },
  {
    _id: "6",
    name: "Metal Packaging",
    slug: { current: "metal-packaging" },
    description: "Industrial metal containers and packaging for hazardous and heavy materials. Built to international safety standards with corrosion-resistant coatings.",
    category: "Metal Products",
    mainImage: "/images/products/metal-packaging.png",
    specs: [
      { label: "Material", value: "MS / GI Steel" },
      { label: "Capacity", value: "20L to 200L" },
      { label: "Coating", value: "Epoxy / Powder" },
      { label: "Standards", value: "IS / UN" },
      { label: "Reconditioned", value: "Available" },
    ],
    industries: ["Chemicals", "Petroleum", "Industrial"],
  },
  {
    _id: "7",
    name: "Vacuum Packaging",
    slug: { current: "vacuum-packaging" },
    description: "Specialized vacuum packaging for sensitive equipment and machinery. Multi-layer barrier films for moisture and corrosion protection during long-term storage and ocean transit.",
    category: "Specialty",
    mainImage: "/images/products/vacuum-packaging.png",
    specs: [
      { label: "Film Type", value: "VCI / Aluminum" },
      { label: "Layers", value: "Multi-layer barrier" },
      { label: "Application", value: "Machinery / Electronics" },
      { label: "Protection", value: "Moisture + Corrosion" },
      { label: "Desiccant", value: "Included" },
    ],
    industries: ["Automotive", "Defense", "Aerospace"],
  },
  {
    _id: "8",
    name: "EPE Foam Packaging",
    slug: { current: "epe-foam" },
    description: "Custom-molded EPE foam inserts for shock absorption and product protection. Ideal for fragile electronics, glass products, and precision instruments.",
    category: "Foam Products",
    mainImage: "/images/products/epe-foam.png",
    specs: [
      { label: "Material", value: "Expanded Polyethylene" },
      { label: "Density", value: "18–30 kg/m³" },
      { label: "Custom Mold", value: "CNC Cut" },
      { label: "Anti-static", value: "Available" },
      { label: "Recyclable", value: "Yes" },
    ],
    industries: ["Electronics", "Medical", "Automotive"],
  },
  {
    _id: "9",
    name: "Shrink Wrapping",
    slug: { current: "shrink-wrapping" },
    description: "Industrial shrink wrapping services for weather protection and load stabilization. On-site wrapping available for oversized cargo and machinery.",
    category: "Specialty",
    mainImage: "/images/products/shrink-wrapping.png",
    specs: [
      { label: "Film Type", value: "LDPE / Cross-linked" },
      { label: "Thickness", value: "100–300 micron" },
      { label: "UV Resistant", value: "Available" },
      { label: "On-site Service", value: "Yes" },
      { label: "Max Size", value: "No limit" },
    ],
    industries: ["Shipping", "Construction", "Heavy Equipment"],
  },
];

export const fallbackServices = [
  {
    _id: "s1",
    name: "On-Site Packaging",
    slug: { current: "on-site-packaging" },
    icon: "Package",
    shortDescription: "Expert packaging teams deployed to your factory or warehouse for seamless on-site packing operations.",
    description: "Our trained packaging professionals come to your facility with all necessary materials and equipment. We handle everything from assessment to final packing, ensuring your products are ready for safe transit. Available across Tamil Nadu and Gujarat with flexible scheduling to minimize your production downtime.",
  },
  {
    _id: "s2",
    name: "Designated Storage",
    slug: { current: "designated-storage" },
    icon: "Warehouse",
    shortDescription: "Secure warehousing facilities with climate control and inventory management at our Chennai and Gujarat locations.",
    description: "Our warehousing facilities at both Chennai and Gujarat locations offer secure storage solutions for your packaged goods. We provide inventory tracking, material management, and both short-term and long-term storage options near major industrial corridors.",
  },
  {
    _id: "s3",
    name: "Loading & Unloading",
    slug: { current: "loading-unloading" },
    icon: "Truck",
    shortDescription: "Professional loading and unloading services with heavy-duty equipment and trained operators.",
    description: "Our loading and unloading services include crane operations, forklift handling, and manual labor for all types of cargo. We handle oversized and overweight consignments with specialized equipment. Our team is trained in safe handling practices to prevent damage during material movement.",
  },
  {
    _id: "s4",
    name: "Methyl Bromide Fumigation",
    slug: { current: "methyl-bromide-fumigation" },
    icon: "Shield",
    shortDescription: "Certified fumigation services for export-compliant packaging meeting ISPM-15 international standards.",
    description: "We provide certified Methyl Bromide fumigation and heat treatment services for all wooden packaging materials. Our treatments comply with ISPM-15 international standards, ensuring your exports meet quarantine requirements worldwide. Certification and marking included with every treatment.",
  },
];

export const fallbackClients = [
  { _id: "c1", name: "Grupo Antolin", logo: "https://logo.clearbit.com/antolin.com", industry: "Automotive" },
  { _id: "c2", name: "Nissan", logo: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Nissan_2020_logo.svg", industry: "Automotive" },
  { _id: "c3", name: "Daimler", logo: "https://upload.wikimedia.org/wikipedia/commons/3/36/Daimler_AG_logo.svg", industry: "Automotive" },
  { _id: "c4", name: "Ford", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Ford_Motor_Company_Logo.svg", industry: "Automotive" },
  { _id: "c5", name: "Amazon", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg", industry: "E-commerce" },
  { _id: "c6", name: "CavinKare", logo: "https://logo.clearbit.com/cavinkare.com", industry: "FMCG" },
  { _id: "c7", name: "Suzuki", logo: "https://upload.wikimedia.org/wikipedia/commons/1/12/Suzuki_logo_2.svg", industry: "Automotive" },
];

export const fallbackLocations = [
  {
    _id: "l1",
    name: "Chennai Factory",
    address: "Survey No.10/38, No.125 Orakkadu Village, Ponneri Taluk, Thiruvallur District Chennai - 600067",
    type: "factory",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15535!2d80.1868342!3d13.245219!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a527c099249597f%3A0x11d4b77e3d2a43a5!2sDivine%20Packaging%20Industry!5e0!3m2!1sen!2sin!4v1711200000000!5m2!1sen!2sin",
  },
  {
    _id: "l2",
    name: "Chennai Office",
    address: "No.481/1, Padasalai Street, Mel Ayanambakkam, Chennai - 95",
    type: "office",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3886.136814041793!2d80.1481!3d13.0905!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a5263ca7b7fc31b%3A0x633d7b4dbf6c24!2sMel%20Ayanambakkam%2C%20Chennai%2C%20Tamil%20Nadu!5e0!3m2!1sen!2sin!4v1711200000000!5m2!1sen!2sin",
  },
  {
    _id: "l3",
    name: "Sanand Factory",
    address: "Survey no : 311, sub-plot no:2& 3, Near PCL logistics, Behind sai super pack, Vasodara village sanand taluk, Ahmedabad Dist, Gujarat – 382110",
    type: "factory",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15535!2d72.3086792!3d23.0212148!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x395ea21a9c7b6a99%3A0xc098caa878eccb34!2sDivine%20Packaging%20Industries!5e0!3m2!1sen!2sin!4v1711200000000!5m2!1sen!2sin",
  },
];
